<strong><?php echo link_to('LiveWireSupply - Circuit Breakers, Transformers, and Switchgear', '@homepage', array('title' => 'We have great prices on new and used reconditioned Circuit Breakers, Transformers, Busway, Motor Control and Fuses from brands like Square D, General Electric, Cutler Hammer and stock for Siemens and Bussman Ferraz Shawmut and others.')) ?></strong>
<!-- removed line-breaks between <li>'s to prevent floating and squash the white-space bug -->
<ul id='nav'>
	<li class='first'><?php echo link_to('ABOUT US', '@about_us', array('title' => 'LiveWire Supply was started in 2005 by Adam Messner.  We believe that through great customer service, great prices and product knowledge, we are building relationships that last a lifetime.')) ?></li><li><?php echo link_to('PRODUCTS', '@products', array('title' => 'Circuit Breakers &ndash; Transformers &ndash; Busway &ndash; Fuses &ndash; Motor Control Medium Voltage are the primary product groups we sell &mdash; we shunt trips, ground fault accessories supply contact kits, fuse holders and many more electrical product accessories.')) ?></li><li><?php echo link_to('SELL TO LIVEWIRE', '@sell_to_lws', array('title' => 'We buy Circuit Breakers, New Breakers, Used Circuit Breakers, Transformers, Busway and Bus Plugs and much more.')) ?></li><li><?php echo link_to('CONTACT US', '@contact_us', array('title' => "Call 800&ndash;390&ndash;3299 all day every day&mdash;there's an emergency sales rep always on call.  Normal hours are Pacific Coast 6:30am to 4:40pm")) ?></li><li><?php echo link_to('REQUEST A QUOTE', '@quotes') ?></li><li class='last'>800.390.3299</li>
</ul>
<form id='search' name='search' method='get' action='<?php echo url_for('@part_search') ?>'>
	<p id='cs_links'><a href='http://shopping.netsuite.com/app/site/query/customercenterredirect.nl?c=502106&amp;ext=T' onclick="pageTracker._link(this.href); return false;">Customer Support</a> &nbsp;|&nbsp; <a href='http://shopping.netsuite.com/s.nl?c=502106&amp;sc=3&amp;ext=T' onclick="pageTracker._link(this.href); return false;">View Cart</a> &nbsp;|&nbsp; <a href='http://shopping.netsuite.com/app/site/query/checkoutredirect.nl?c=502106&amp;ext=T&amp;login=T' onclick="pageTracker._link(this.href); return false;">Login</a></p>
	<p><input type='text' size='25' maxlength='50' value='' class='txt' name='q' /><input type='submit' value='' id='srch_btn' class='sbmt' /></p>
</form>
<div id='part_serp' style='display:none;'></div>
